# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 00:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=250, verbose_name='Description')),
                ('client_name', models.CharField(max_length=250, verbose_name='Nom du client')),
                ('client_address', models.CharField(max_length=250, verbose_name='Adresse du client')),
                ('client_phone', models.CharField(max_length=250, verbose_name='Numéro de téléphone du client')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('1', 'Standby'), ('2', 'Fait'), ('3', 'Cancel')], max_length=250)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='job.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='job.Job')),
            ],
        ),
    ]
